# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者姓名', 'verbose_name_plural': '作者姓名'},
        ),
        migrations.AlterModelOptions(
            name='authordetail',
            options={'verbose_name': '作者详情', 'verbose_name_plural': '作者详情'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '书籍', 'verbose_name_plural': '书籍'},
        ),
        migrations.AlterModelOptions(
            name='publish',
            options={'verbose_name': '出版商', 'verbose_name_plural': '出版商'},
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='address',
            field=models.CharField(max_length=50, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hello.Author', verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='birthday',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='sex',
            field=models.BooleanField(choices=[(0, '男'), (1, '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='hello.Author', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(verbose_name='出版日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Publish', verbose_name='出版商'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='address',
            field=models.CharField(max_length=50, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='city',
            field=models.CharField(max_length=60, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='country',
            field=models.CharField(max_length=50, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='name',
            field=models.CharField(max_length=30, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='satee_procince',
            field=models.CharField(max_length=30, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='website',
            field=models.URLField(verbose_name='网址'),
        ),
    ]
